//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meteor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationFile
    {
        public int Id { get; set; }
        public string name { get; set; }
        public bool present { get; set; }
        public string folder { get; set; }
    }
}
