//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meteor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkinLibrary
    {
        public int Id { get; set; }
        public int slot { get; set; }
        public int workspace_id { get; set; }
        public int character_id { get; set; }
        public int skin_id { get; set; }
        public int nameplate_id { get; set; }
        public bool library_lock { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Skin Skin { get; set; }
        public virtual Workspace Workspace { get; set; }
        public virtual Nameplate Nameplate { get; set; }
    }
}
