//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meteor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skin()
        {
            this.SkinLibraries = new HashSet<SkinLibrary>();
        }
    
        public int Id { get; set; }
        public int character_id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string skin_models { get; set; }
        public string skin_csps { get; set; }
        public Nullable<int> gb_uid { get; set; }
        public string model_hash_1 { get; set; }
        public string model_hash_2 { get; set; }
        public string csp_hash_1 { get; set; }
        public string csp_hash_2 { get; set; }
        public string csp_hash_3 { get; set; }
        public string csp_hash_4 { get; set; }
        public Nullable<bool> skinLock { get; set; }
    
        public virtual Character Character { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkinLibrary> SkinLibraries { get; set; }
    }
}
