//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meteor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meteor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update skins set name = &apos;Pink&apos; where id = 416.
        /// </summary>
        internal static string command {
            get {
                return ResourceManager.GetString("command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;package version=&quot;0.8.0.4&quot;&gt;
        ///  &lt;patchnote version=&quot;0.8.0.4&quot;&gt;
        ///    &lt;patch&gt;Filebank has an All Characters option&lt;/patch&gt;
        ///    &lt;patch&gt;All Characters is selected upon launch&lt;/patch&gt;
        ///    &lt;patch&gt;Pressing del will serve as the same function as the delete permanently button&lt;/patch&gt;
        ///  &lt;/patchnote&gt;
        ///  &lt;patchnote version=&quot;0.8.0.3&quot;&gt;
        ///    &lt;patch&gt;Minor interface fix&lt;/patch&gt;
        ///  &lt;/patchnote&gt;
        ///  &lt;patchnote version=&quot;0.8.0.2&quot;&gt;
        ///    &lt;patch&gt;Safer Downloads&lt;/patch&gt;
        ///    &lt;patch&gt;Download Fix Issue&lt;/patch&gt;
        ///  &lt;/patchnote&gt;
        ///  &lt;pat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string patchnotes {
            get {
                return ResourceManager.GetString("patchnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;package&gt;
        ///  &lt;file version=&quot;0_8_0_5&quot;&gt;Meteor.exe&lt;/file&gt;
        ///  &lt;file version=&quot;0_8_0_5&quot;&gt;command.txt&lt;/file&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string updatefiles {
            get {
                return ResourceManager.GetString("updatefiles", resourceCulture);
            }
        }
    }
}
